# Generated by Django 3.0.4 on 2020-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_url_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='domage',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
