# Generated by Django 3.0.4 on 2020-05-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_url_domage'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='varab',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
