# Generated by Django 3.0.4 on 2020-05-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_url_varab'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='redir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
