# Generated by Django 3.0.4 on 2020-05-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_url_redir'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='var3',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='var5',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
