# Generated by Django 3.0.4 on 2020-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200518_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ipadd',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='ipcity',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='ipcountry',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='iplatitude',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='iplongitude',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='ipstate',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
